name: Successify
favicon: null
layout_spectrum: 0.76433
typography_spectrum: 0.78939
title: 'Make a Life that Matters!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#837e7e'
    - '#1dab2b'
    - '#c92415'
    - '#c1bebe'
  brandStrength: 1
  lightness: 0.6539711246732622
  saturation: 0.9308789174538106
  rhythmicContrast: 0.5
purpose: []
